[package]
name = "extrasafe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seccomp = { git = "https://github.com/polachok/seccomp", rev = "d04f8ac5a8bd" }
libc = "^0.2"
thiserror = "^1"
syscalls = "^0.5"

[dev-dependencies]
tempfile = "^3"
